### ISSUE TITLE
Move image to sasanarakkha namespace

### ISSUE THREAD

**Issue by bergentroll** [sasanarakkha/document-build-actions#1]
There is an image `bergentroll/pali-english-recitations-builder` on hub.docker.com which could also be moved here, but I lack  `create_package` permission. It seems it is [sasanarakkha](https://github.com/sasanarakkha) membership required.

@paladhammika :pray::pray::pray:

**Comment by paladhammika** [comment]
Bergen I've been in Thailand an AFK for the last few months. I'll grant you maintain permissions.

**Comment by bergentroll** [comment]
Thank you, bhante. But there is still a `permission_denied: create_package` error. Seems, the public checkbox should be enabled on package settings page (should be somewhere [here](https://github.com/organizations/sasanarakkha/settings/packages)):

![settings](https://github.com/sasanarakkha/document-build-actions/assets/14995027/b8e23596-fe31-4a51-b9fe-471ec69b6865)

Also image publisher must be the organization member, not just repository member. You also may just push an image with Docker by yourself:

```bash
# Get the latest image
sudo docker pull bergentroll/pali-english-recitations-builder

# Add new tag to the image
sudo docker tag bergentroll/pali-english-recitations-builder ghcr.io/sasanarakkha/document-build-actions/pali-english-recitations-builder

# Login in  GitHub registry, it needs "personal access token" as password, which can be created on page
# https://github.com/settings/tokens
sudo docker login ghcr.io

# Publish the image to this namespace
sudo docker push ghcr.io/sasanarakkha/document-build-actions/pali-english-recitations-builder
```

Than image can be linked to the repository.

**Comment by paladhammika** [comment]
Been away for a while again. I just ran the above commands.

**Comment by bergentroll** [comment]
Done with [GitHub Actions](https://github.com/sasanarakkha/document-build-actions/blob/main/.github/workflows/docker-publish.yml).

**Comment by paladhammika** [comment]
Sādhu. Thanks for everything. The auto-build process was a great help. 

We are in the final stages of editing and soon hope to record some audio of the SBS monks chanting.

**Comment by bergentroll** [comment]
:pray: :pray: :pray:

> hope to record some audio of the SBS monks chanting

Great! Does someone will help you to make records with good equipment?

**Comment by paladhammika** [comment]
We hope so. Looking for a good recording studio.
